version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.tauron.mindful-web.parameter1.com}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  multi:
    <<: *newsletter-cmd
    working_dir: /root/tenants/multi
    environment:
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 21094
      LIVERELOAD_PORT: 31094
      TENANT_KEY: indm_multi
    ports:
      - "21094:80"
      - "31094:31094"

volumes:
  yarn-cache: {}
